#!/usr/local/bin/dumb-init /bin/bash

NGINX_TOML='/etc/nginx/nginx.conf'

#traefik log level
: ${NGINX_LOG_LEVEL:-debug} && \
sed -i -e "s@{{NGINX_LOG_LEVEL}}@${NGINX_LOG_LEVEL}@g" ${NGINX_TOML}

#traefik http port
: ${NGINX_HTTP_PORT:-80} && \
sed -i -e "s@{{NGINX_HTTP_PORT}}@${NGINX_HTTP_PORT}@g" ${NGINX_TOML}

#traefik https port
: ${NGINX_HTTPS_PORT:-443} && \
sed -i -e "s@{{NGINX_HTTPS_PORT}}@${NGINX_HTTPS_PORT}@g" ${NGINX_TOML}

function checkNetwork {
    echo "[ Checking container ip... ]"
    a="$(ip a s dev eth0 &> /dev/null; echo $?)"
    while  [ $a -eq 1 ];
    do
        a="$(ip a s dev eth0 &> /dev/null; echo $?)" 
        sleep 1
    done

    echo "[ Checking container connectivity... ]"
    b="$(fping -c 1 rancher-metadata.rancher.internal &> /dev/null; echo $?)"
    while [ $b -eq 1 ];
    do
        b="$(fping -c 1 rancher-metadata.rancher.internal &> /dev/null; echo $?)"
        sleep 1
    done
}

checkNetwork


exec /opt/tools/confd/bin/confd -interval ${CONFD_INTERVAL} -confdir /opt/tools/confd/etc -backend rancher -prefix ${CONFD_PREFIX}
